app = "myproxy"   # change this

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8888
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 8888
    handlers = ["tls", "http"]
